// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userbalancecredit"
)

// UserBalanceCreditUpdate is the builder for updating UserBalanceCredit entities.
type UserBalanceCreditUpdate struct {
	config
	hooks    []Hook
	mutation *UserBalanceCreditMutation
}

// Where appends a list predicates to the UserBalanceCreditUpdate builder.
func (_u *UserBalanceCreditUpdate) Where(ps ...predicate.UserBalanceCredit) *UserBalanceCreditUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserBalanceCreditUpdate) SetUserID(v int64) *UserBalanceCreditUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserBalanceCreditUpdate) SetNillableUserID(v *int64) *UserBalanceCreditUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *UserBalanceCreditUpdate) SetSourceType(v string) *UserBalanceCreditUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *UserBalanceCreditUpdate) SetNillableSourceType(v *string) *UserBalanceCreditUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *UserBalanceCreditUpdate) SetSourceID(v string) *UserBalanceCreditUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *UserBalanceCreditUpdate) SetNillableSourceID(v *string) *UserBalanceCreditUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetSourceCode sets the "source_code" field.
func (_u *UserBalanceCreditUpdate) SetSourceCode(v string) *UserBalanceCreditUpdate {
	_u.mutation.SetSourceCode(v)
	return _u
}

// SetNillableSourceCode sets the "source_code" field if the given value is not nil.
func (_u *UserBalanceCreditUpdate) SetNillableSourceCode(v *string) *UserBalanceCreditUpdate {
	if v != nil {
		_u.SetSourceCode(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *UserBalanceCreditUpdate) SetAmount(v float64) *UserBalanceCreditUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *UserBalanceCreditUpdate) SetNillableAmount(v *float64) *UserBalanceCreditUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *UserBalanceCreditUpdate) AddAmount(v float64) *UserBalanceCreditUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetRemainingAmount sets the "remaining_amount" field.
func (_u *UserBalanceCreditUpdate) SetRemainingAmount(v float64) *UserBalanceCreditUpdate {
	_u.mutation.ResetRemainingAmount()
	_u.mutation.SetRemainingAmount(v)
	return _u
}

// SetNillableRemainingAmount sets the "remaining_amount" field if the given value is not nil.
func (_u *UserBalanceCreditUpdate) SetNillableRemainingAmount(v *float64) *UserBalanceCreditUpdate {
	if v != nil {
		_u.SetRemainingAmount(*v)
	}
	return _u
}

// AddRemainingAmount adds value to the "remaining_amount" field.
func (_u *UserBalanceCreditUpdate) AddRemainingAmount(v float64) *UserBalanceCreditUpdate {
	_u.mutation.AddRemainingAmount(v)
	return _u
}

// SetSettledUntilDate sets the "settled_until_date" field.
func (_u *UserBalanceCreditUpdate) SetSettledUntilDate(v time.Time) *UserBalanceCreditUpdate {
	_u.mutation.SetSettledUntilDate(v)
	return _u
}

// SetNillableSettledUntilDate sets the "settled_until_date" field if the given value is not nil.
func (_u *UserBalanceCreditUpdate) SetNillableSettledUntilDate(v *time.Time) *UserBalanceCreditUpdate {
	if v != nil {
		_u.SetSettledUntilDate(*v)
	}
	return _u
}

// ClearSettledUntilDate clears the value of the "settled_until_date" field.
func (_u *UserBalanceCreditUpdate) ClearSettledUntilDate() *UserBalanceCreditUpdate {
	_u.mutation.ClearSettledUntilDate()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserBalanceCreditUpdate) SetExpiresAt(v time.Time) *UserBalanceCreditUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserBalanceCreditUpdate) SetNillableExpiresAt(v *time.Time) *UserBalanceCreditUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UserBalanceCreditUpdate) ClearExpiresAt() *UserBalanceCreditUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *UserBalanceCreditUpdate) SetExpiredAt(v time.Time) *UserBalanceCreditUpdate {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *UserBalanceCreditUpdate) SetNillableExpiredAt(v *time.Time) *UserBalanceCreditUpdate {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *UserBalanceCreditUpdate) ClearExpiredAt() *UserBalanceCreditUpdate {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserBalanceCreditUpdate) SetStatus(v string) *UserBalanceCreditUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserBalanceCreditUpdate) SetNillableStatus(v *string) *UserBalanceCreditUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserBalanceCreditUpdate) SetUpdatedAt(v time.Time) *UserBalanceCreditUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserBalanceCreditUpdate) SetUser(v *User) *UserBalanceCreditUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserBalanceCreditMutation object of the builder.
func (_u *UserBalanceCreditUpdate) Mutation() *UserBalanceCreditMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserBalanceCreditUpdate) ClearUser() *UserBalanceCreditUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserBalanceCreditUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserBalanceCreditUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserBalanceCreditUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserBalanceCreditUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserBalanceCreditUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userbalancecredit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserBalanceCreditUpdate) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := userbalancecredit.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "UserBalanceCredit.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceID(); ok {
		if err := userbalancecredit.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "UserBalanceCredit.source_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceCode(); ok {
		if err := userbalancecredit.SourceCodeValidator(v); err != nil {
			return &ValidationError{Name: "source_code", err: fmt.Errorf(`ent: validator failed for field "UserBalanceCredit.source_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := userbalancecredit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserBalanceCredit.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserBalanceCredit.user"`)
	}
	return nil
}

func (_u *UserBalanceCreditUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userbalancecredit.Table, userbalancecredit.Columns, sqlgraph.NewFieldSpec(userbalancecredit.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(userbalancecredit.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(userbalancecredit.FieldSourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceCode(); ok {
		_spec.SetField(userbalancecredit.FieldSourceCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(userbalancecredit.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(userbalancecredit.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RemainingAmount(); ok {
		_spec.SetField(userbalancecredit.FieldRemainingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRemainingAmount(); ok {
		_spec.AddField(userbalancecredit.FieldRemainingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SettledUntilDate(); ok {
		_spec.SetField(userbalancecredit.FieldSettledUntilDate, field.TypeTime, value)
	}
	if _u.mutation.SettledUntilDateCleared() {
		_spec.ClearField(userbalancecredit.FieldSettledUntilDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(userbalancecredit.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(userbalancecredit.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(userbalancecredit.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(userbalancecredit.FieldExpiredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(userbalancecredit.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userbalancecredit.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbalancecredit.UserTable,
			Columns: []string{userbalancecredit.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbalancecredit.UserTable,
			Columns: []string{userbalancecredit.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userbalancecredit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserBalanceCreditUpdateOne is the builder for updating a single UserBalanceCredit entity.
type UserBalanceCreditUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserBalanceCreditMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserBalanceCreditUpdateOne) SetUserID(v int64) *UserBalanceCreditUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserBalanceCreditUpdateOne) SetNillableUserID(v *int64) *UserBalanceCreditUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *UserBalanceCreditUpdateOne) SetSourceType(v string) *UserBalanceCreditUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *UserBalanceCreditUpdateOne) SetNillableSourceType(v *string) *UserBalanceCreditUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *UserBalanceCreditUpdateOne) SetSourceID(v string) *UserBalanceCreditUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *UserBalanceCreditUpdateOne) SetNillableSourceID(v *string) *UserBalanceCreditUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetSourceCode sets the "source_code" field.
func (_u *UserBalanceCreditUpdateOne) SetSourceCode(v string) *UserBalanceCreditUpdateOne {
	_u.mutation.SetSourceCode(v)
	return _u
}

// SetNillableSourceCode sets the "source_code" field if the given value is not nil.
func (_u *UserBalanceCreditUpdateOne) SetNillableSourceCode(v *string) *UserBalanceCreditUpdateOne {
	if v != nil {
		_u.SetSourceCode(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *UserBalanceCreditUpdateOne) SetAmount(v float64) *UserBalanceCreditUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *UserBalanceCreditUpdateOne) SetNillableAmount(v *float64) *UserBalanceCreditUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *UserBalanceCreditUpdateOne) AddAmount(v float64) *UserBalanceCreditUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetRemainingAmount sets the "remaining_amount" field.
func (_u *UserBalanceCreditUpdateOne) SetRemainingAmount(v float64) *UserBalanceCreditUpdateOne {
	_u.mutation.ResetRemainingAmount()
	_u.mutation.SetRemainingAmount(v)
	return _u
}

// SetNillableRemainingAmount sets the "remaining_amount" field if the given value is not nil.
func (_u *UserBalanceCreditUpdateOne) SetNillableRemainingAmount(v *float64) *UserBalanceCreditUpdateOne {
	if v != nil {
		_u.SetRemainingAmount(*v)
	}
	return _u
}

// AddRemainingAmount adds value to the "remaining_amount" field.
func (_u *UserBalanceCreditUpdateOne) AddRemainingAmount(v float64) *UserBalanceCreditUpdateOne {
	_u.mutation.AddRemainingAmount(v)
	return _u
}

// SetSettledUntilDate sets the "settled_until_date" field.
func (_u *UserBalanceCreditUpdateOne) SetSettledUntilDate(v time.Time) *UserBalanceCreditUpdateOne {
	_u.mutation.SetSettledUntilDate(v)
	return _u
}

// SetNillableSettledUntilDate sets the "settled_until_date" field if the given value is not nil.
func (_u *UserBalanceCreditUpdateOne) SetNillableSettledUntilDate(v *time.Time) *UserBalanceCreditUpdateOne {
	if v != nil {
		_u.SetSettledUntilDate(*v)
	}
	return _u
}

// ClearSettledUntilDate clears the value of the "settled_until_date" field.
func (_u *UserBalanceCreditUpdateOne) ClearSettledUntilDate() *UserBalanceCreditUpdateOne {
	_u.mutation.ClearSettledUntilDate()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserBalanceCreditUpdateOne) SetExpiresAt(v time.Time) *UserBalanceCreditUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserBalanceCreditUpdateOne) SetNillableExpiresAt(v *time.Time) *UserBalanceCreditUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UserBalanceCreditUpdateOne) ClearExpiresAt() *UserBalanceCreditUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *UserBalanceCreditUpdateOne) SetExpiredAt(v time.Time) *UserBalanceCreditUpdateOne {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *UserBalanceCreditUpdateOne) SetNillableExpiredAt(v *time.Time) *UserBalanceCreditUpdateOne {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *UserBalanceCreditUpdateOne) ClearExpiredAt() *UserBalanceCreditUpdateOne {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserBalanceCreditUpdateOne) SetStatus(v string) *UserBalanceCreditUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserBalanceCreditUpdateOne) SetNillableStatus(v *string) *UserBalanceCreditUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserBalanceCreditUpdateOne) SetUpdatedAt(v time.Time) *UserBalanceCreditUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserBalanceCreditUpdateOne) SetUser(v *User) *UserBalanceCreditUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserBalanceCreditMutation object of the builder.
func (_u *UserBalanceCreditUpdateOne) Mutation() *UserBalanceCreditMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserBalanceCreditUpdateOne) ClearUser() *UserBalanceCreditUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserBalanceCreditUpdate builder.
func (_u *UserBalanceCreditUpdateOne) Where(ps ...predicate.UserBalanceCredit) *UserBalanceCreditUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserBalanceCreditUpdateOne) Select(field string, fields ...string) *UserBalanceCreditUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserBalanceCredit entity.
func (_u *UserBalanceCreditUpdateOne) Save(ctx context.Context) (*UserBalanceCredit, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserBalanceCreditUpdateOne) SaveX(ctx context.Context) *UserBalanceCredit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserBalanceCreditUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserBalanceCreditUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserBalanceCreditUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userbalancecredit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserBalanceCreditUpdateOne) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := userbalancecredit.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "UserBalanceCredit.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceID(); ok {
		if err := userbalancecredit.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "UserBalanceCredit.source_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceCode(); ok {
		if err := userbalancecredit.SourceCodeValidator(v); err != nil {
			return &ValidationError{Name: "source_code", err: fmt.Errorf(`ent: validator failed for field "UserBalanceCredit.source_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := userbalancecredit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserBalanceCredit.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserBalanceCredit.user"`)
	}
	return nil
}

func (_u *UserBalanceCreditUpdateOne) sqlSave(ctx context.Context) (_node *UserBalanceCredit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userbalancecredit.Table, userbalancecredit.Columns, sqlgraph.NewFieldSpec(userbalancecredit.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserBalanceCredit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userbalancecredit.FieldID)
		for _, f := range fields {
			if !userbalancecredit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userbalancecredit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(userbalancecredit.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(userbalancecredit.FieldSourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceCode(); ok {
		_spec.SetField(userbalancecredit.FieldSourceCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(userbalancecredit.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(userbalancecredit.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RemainingAmount(); ok {
		_spec.SetField(userbalancecredit.FieldRemainingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRemainingAmount(); ok {
		_spec.AddField(userbalancecredit.FieldRemainingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SettledUntilDate(); ok {
		_spec.SetField(userbalancecredit.FieldSettledUntilDate, field.TypeTime, value)
	}
	if _u.mutation.SettledUntilDateCleared() {
		_spec.ClearField(userbalancecredit.FieldSettledUntilDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(userbalancecredit.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(userbalancecredit.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(userbalancecredit.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(userbalancecredit.FieldExpiredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(userbalancecredit.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userbalancecredit.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbalancecredit.UserTable,
			Columns: []string{userbalancecredit.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbalancecredit.UserTable,
			Columns: []string{userbalancecredit.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserBalanceCredit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userbalancecredit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
