// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userbalancecredit"
)

// UserBalanceCreditCreate is the builder for creating a UserBalanceCredit entity.
type UserBalanceCreditCreate struct {
	config
	mutation *UserBalanceCreditMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserBalanceCreditCreate) SetUserID(v int64) *UserBalanceCreditCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *UserBalanceCreditCreate) SetSourceType(v string) *UserBalanceCreditCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *UserBalanceCreditCreate) SetSourceID(v string) *UserBalanceCreditCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_c *UserBalanceCreditCreate) SetNillableSourceID(v *string) *UserBalanceCreditCreate {
	if v != nil {
		_c.SetSourceID(*v)
	}
	return _c
}

// SetSourceCode sets the "source_code" field.
func (_c *UserBalanceCreditCreate) SetSourceCode(v string) *UserBalanceCreditCreate {
	_c.mutation.SetSourceCode(v)
	return _c
}

// SetNillableSourceCode sets the "source_code" field if the given value is not nil.
func (_c *UserBalanceCreditCreate) SetNillableSourceCode(v *string) *UserBalanceCreditCreate {
	if v != nil {
		_c.SetSourceCode(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *UserBalanceCreditCreate) SetAmount(v float64) *UserBalanceCreditCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetRemainingAmount sets the "remaining_amount" field.
func (_c *UserBalanceCreditCreate) SetRemainingAmount(v float64) *UserBalanceCreditCreate {
	_c.mutation.SetRemainingAmount(v)
	return _c
}

// SetSettledUntilDate sets the "settled_until_date" field.
func (_c *UserBalanceCreditCreate) SetSettledUntilDate(v time.Time) *UserBalanceCreditCreate {
	_c.mutation.SetSettledUntilDate(v)
	return _c
}

// SetNillableSettledUntilDate sets the "settled_until_date" field if the given value is not nil.
func (_c *UserBalanceCreditCreate) SetNillableSettledUntilDate(v *time.Time) *UserBalanceCreditCreate {
	if v != nil {
		_c.SetSettledUntilDate(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserBalanceCreditCreate) SetExpiresAt(v time.Time) *UserBalanceCreditCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *UserBalanceCreditCreate) SetNillableExpiresAt(v *time.Time) *UserBalanceCreditCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetExpiredAt sets the "expired_at" field.
func (_c *UserBalanceCreditCreate) SetExpiredAt(v time.Time) *UserBalanceCreditCreate {
	_c.mutation.SetExpiredAt(v)
	return _c
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_c *UserBalanceCreditCreate) SetNillableExpiredAt(v *time.Time) *UserBalanceCreditCreate {
	if v != nil {
		_c.SetExpiredAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserBalanceCreditCreate) SetStatus(v string) *UserBalanceCreditCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserBalanceCreditCreate) SetNillableStatus(v *string) *UserBalanceCreditCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserBalanceCreditCreate) SetCreatedAt(v time.Time) *UserBalanceCreditCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserBalanceCreditCreate) SetNillableCreatedAt(v *time.Time) *UserBalanceCreditCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserBalanceCreditCreate) SetUpdatedAt(v time.Time) *UserBalanceCreditCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserBalanceCreditCreate) SetNillableUpdatedAt(v *time.Time) *UserBalanceCreditCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserBalanceCreditCreate) SetUser(v *User) *UserBalanceCreditCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserBalanceCreditMutation object of the builder.
func (_c *UserBalanceCreditCreate) Mutation() *UserBalanceCreditMutation {
	return _c.mutation
}

// Save creates the UserBalanceCredit in the database.
func (_c *UserBalanceCreditCreate) Save(ctx context.Context) (*UserBalanceCredit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserBalanceCreditCreate) SaveX(ctx context.Context) *UserBalanceCredit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserBalanceCreditCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserBalanceCreditCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserBalanceCreditCreate) defaults() {
	if _, ok := _c.mutation.SourceID(); !ok {
		v := userbalancecredit.DefaultSourceID
		_c.mutation.SetSourceID(v)
	}
	if _, ok := _c.mutation.SourceCode(); !ok {
		v := userbalancecredit.DefaultSourceCode
		_c.mutation.SetSourceCode(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := userbalancecredit.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userbalancecredit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userbalancecredit.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserBalanceCreditCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserBalanceCredit.user_id"`)}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "UserBalanceCredit.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := userbalancecredit.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "UserBalanceCredit.source_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "UserBalanceCredit.source_id"`)}
	}
	if v, ok := _c.mutation.SourceID(); ok {
		if err := userbalancecredit.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "UserBalanceCredit.source_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceCode(); !ok {
		return &ValidationError{Name: "source_code", err: errors.New(`ent: missing required field "UserBalanceCredit.source_code"`)}
	}
	if v, ok := _c.mutation.SourceCode(); ok {
		if err := userbalancecredit.SourceCodeValidator(v); err != nil {
			return &ValidationError{Name: "source_code", err: fmt.Errorf(`ent: validator failed for field "UserBalanceCredit.source_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "UserBalanceCredit.amount"`)}
	}
	if _, ok := _c.mutation.RemainingAmount(); !ok {
		return &ValidationError{Name: "remaining_amount", err: errors.New(`ent: missing required field "UserBalanceCredit.remaining_amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserBalanceCredit.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := userbalancecredit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserBalanceCredit.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserBalanceCredit.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserBalanceCredit.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserBalanceCredit.user"`)}
	}
	return nil
}

func (_c *UserBalanceCreditCreate) sqlSave(ctx context.Context) (*UserBalanceCredit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserBalanceCreditCreate) createSpec() (*UserBalanceCredit, *sqlgraph.CreateSpec) {
	var (
		_node = &UserBalanceCredit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userbalancecredit.Table, sqlgraph.NewFieldSpec(userbalancecredit.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(userbalancecredit.FieldSourceType, field.TypeString, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(userbalancecredit.FieldSourceID, field.TypeString, value)
		_node.SourceID = value
	}
	if value, ok := _c.mutation.SourceCode(); ok {
		_spec.SetField(userbalancecredit.FieldSourceCode, field.TypeString, value)
		_node.SourceCode = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(userbalancecredit.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.RemainingAmount(); ok {
		_spec.SetField(userbalancecredit.FieldRemainingAmount, field.TypeFloat64, value)
		_node.RemainingAmount = value
	}
	if value, ok := _c.mutation.SettledUntilDate(); ok {
		_spec.SetField(userbalancecredit.FieldSettledUntilDate, field.TypeTime, value)
		_node.SettledUntilDate = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(userbalancecredit.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.ExpiredAt(); ok {
		_spec.SetField(userbalancecredit.FieldExpiredAt, field.TypeTime, value)
		_node.ExpiredAt = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(userbalancecredit.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userbalancecredit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userbalancecredit.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbalancecredit.UserTable,
			Columns: []string{userbalancecredit.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserBalanceCredit.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserBalanceCreditUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserBalanceCreditCreate) OnConflict(opts ...sql.ConflictOption) *UserBalanceCreditUpsertOne {
	_c.conflict = opts
	return &UserBalanceCreditUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserBalanceCredit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserBalanceCreditCreate) OnConflictColumns(columns ...string) *UserBalanceCreditUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserBalanceCreditUpsertOne{
		create: _c,
	}
}

type (
	// UserBalanceCreditUpsertOne is the builder for "upsert"-ing
	//  one UserBalanceCredit node.
	UserBalanceCreditUpsertOne struct {
		create *UserBalanceCreditCreate
	}

	// UserBalanceCreditUpsert is the "OnConflict" setter.
	UserBalanceCreditUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserBalanceCreditUpsert) SetUserID(v int64) *UserBalanceCreditUpsert {
	u.Set(userbalancecredit.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserBalanceCreditUpsert) UpdateUserID() *UserBalanceCreditUpsert {
	u.SetExcluded(userbalancecredit.FieldUserID)
	return u
}

// SetSourceType sets the "source_type" field.
func (u *UserBalanceCreditUpsert) SetSourceType(v string) *UserBalanceCreditUpsert {
	u.Set(userbalancecredit.FieldSourceType, v)
	return u
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *UserBalanceCreditUpsert) UpdateSourceType() *UserBalanceCreditUpsert {
	u.SetExcluded(userbalancecredit.FieldSourceType)
	return u
}

// SetSourceID sets the "source_id" field.
func (u *UserBalanceCreditUpsert) SetSourceID(v string) *UserBalanceCreditUpsert {
	u.Set(userbalancecredit.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *UserBalanceCreditUpsert) UpdateSourceID() *UserBalanceCreditUpsert {
	u.SetExcluded(userbalancecredit.FieldSourceID)
	return u
}

// SetSourceCode sets the "source_code" field.
func (u *UserBalanceCreditUpsert) SetSourceCode(v string) *UserBalanceCreditUpsert {
	u.Set(userbalancecredit.FieldSourceCode, v)
	return u
}

// UpdateSourceCode sets the "source_code" field to the value that was provided on create.
func (u *UserBalanceCreditUpsert) UpdateSourceCode() *UserBalanceCreditUpsert {
	u.SetExcluded(userbalancecredit.FieldSourceCode)
	return u
}

// SetAmount sets the "amount" field.
func (u *UserBalanceCreditUpsert) SetAmount(v float64) *UserBalanceCreditUpsert {
	u.Set(userbalancecredit.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserBalanceCreditUpsert) UpdateAmount() *UserBalanceCreditUpsert {
	u.SetExcluded(userbalancecredit.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *UserBalanceCreditUpsert) AddAmount(v float64) *UserBalanceCreditUpsert {
	u.Add(userbalancecredit.FieldAmount, v)
	return u
}

// SetRemainingAmount sets the "remaining_amount" field.
func (u *UserBalanceCreditUpsert) SetRemainingAmount(v float64) *UserBalanceCreditUpsert {
	u.Set(userbalancecredit.FieldRemainingAmount, v)
	return u
}

// UpdateRemainingAmount sets the "remaining_amount" field to the value that was provided on create.
func (u *UserBalanceCreditUpsert) UpdateRemainingAmount() *UserBalanceCreditUpsert {
	u.SetExcluded(userbalancecredit.FieldRemainingAmount)
	return u
}

// AddRemainingAmount adds v to the "remaining_amount" field.
func (u *UserBalanceCreditUpsert) AddRemainingAmount(v float64) *UserBalanceCreditUpsert {
	u.Add(userbalancecredit.FieldRemainingAmount, v)
	return u
}

// SetSettledUntilDate sets the "settled_until_date" field.
func (u *UserBalanceCreditUpsert) SetSettledUntilDate(v time.Time) *UserBalanceCreditUpsert {
	u.Set(userbalancecredit.FieldSettledUntilDate, v)
	return u
}

// UpdateSettledUntilDate sets the "settled_until_date" field to the value that was provided on create.
func (u *UserBalanceCreditUpsert) UpdateSettledUntilDate() *UserBalanceCreditUpsert {
	u.SetExcluded(userbalancecredit.FieldSettledUntilDate)
	return u
}

// ClearSettledUntilDate clears the value of the "settled_until_date" field.
func (u *UserBalanceCreditUpsert) ClearSettledUntilDate() *UserBalanceCreditUpsert {
	u.SetNull(userbalancecredit.FieldSettledUntilDate)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserBalanceCreditUpsert) SetExpiresAt(v time.Time) *UserBalanceCreditUpsert {
	u.Set(userbalancecredit.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserBalanceCreditUpsert) UpdateExpiresAt() *UserBalanceCreditUpsert {
	u.SetExcluded(userbalancecredit.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UserBalanceCreditUpsert) ClearExpiresAt() *UserBalanceCreditUpsert {
	u.SetNull(userbalancecredit.FieldExpiresAt)
	return u
}

// SetExpiredAt sets the "expired_at" field.
func (u *UserBalanceCreditUpsert) SetExpiredAt(v time.Time) *UserBalanceCreditUpsert {
	u.Set(userbalancecredit.FieldExpiredAt, v)
	return u
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *UserBalanceCreditUpsert) UpdateExpiredAt() *UserBalanceCreditUpsert {
	u.SetExcluded(userbalancecredit.FieldExpiredAt)
	return u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (u *UserBalanceCreditUpsert) ClearExpiredAt() *UserBalanceCreditUpsert {
	u.SetNull(userbalancecredit.FieldExpiredAt)
	return u
}

// SetStatus sets the "status" field.
func (u *UserBalanceCreditUpsert) SetStatus(v string) *UserBalanceCreditUpsert {
	u.Set(userbalancecredit.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserBalanceCreditUpsert) UpdateStatus() *UserBalanceCreditUpsert {
	u.SetExcluded(userbalancecredit.FieldStatus)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserBalanceCreditUpsert) SetUpdatedAt(v time.Time) *UserBalanceCreditUpsert {
	u.Set(userbalancecredit.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserBalanceCreditUpsert) UpdateUpdatedAt() *UserBalanceCreditUpsert {
	u.SetExcluded(userbalancecredit.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserBalanceCredit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserBalanceCreditUpsertOne) UpdateNewValues() *UserBalanceCreditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userbalancecredit.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserBalanceCredit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserBalanceCreditUpsertOne) Ignore() *UserBalanceCreditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserBalanceCreditUpsertOne) DoNothing() *UserBalanceCreditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserBalanceCreditCreate.OnConflict
// documentation for more info.
func (u *UserBalanceCreditUpsertOne) Update(set func(*UserBalanceCreditUpsert)) *UserBalanceCreditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserBalanceCreditUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserBalanceCreditUpsertOne) SetUserID(v int64) *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertOne) UpdateUserID() *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateUserID()
	})
}

// SetSourceType sets the "source_type" field.
func (u *UserBalanceCreditUpsertOne) SetSourceType(v string) *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertOne) UpdateSourceType() *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceID sets the "source_id" field.
func (u *UserBalanceCreditUpsertOne) SetSourceID(v string) *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertOne) UpdateSourceID() *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateSourceID()
	})
}

// SetSourceCode sets the "source_code" field.
func (u *UserBalanceCreditUpsertOne) SetSourceCode(v string) *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetSourceCode(v)
	})
}

// UpdateSourceCode sets the "source_code" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertOne) UpdateSourceCode() *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateSourceCode()
	})
}

// SetAmount sets the "amount" field.
func (u *UserBalanceCreditUpsertOne) SetAmount(v float64) *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *UserBalanceCreditUpsertOne) AddAmount(v float64) *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertOne) UpdateAmount() *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateAmount()
	})
}

// SetRemainingAmount sets the "remaining_amount" field.
func (u *UserBalanceCreditUpsertOne) SetRemainingAmount(v float64) *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetRemainingAmount(v)
	})
}

// AddRemainingAmount adds v to the "remaining_amount" field.
func (u *UserBalanceCreditUpsertOne) AddRemainingAmount(v float64) *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.AddRemainingAmount(v)
	})
}

// UpdateRemainingAmount sets the "remaining_amount" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertOne) UpdateRemainingAmount() *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateRemainingAmount()
	})
}

// SetSettledUntilDate sets the "settled_until_date" field.
func (u *UserBalanceCreditUpsertOne) SetSettledUntilDate(v time.Time) *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetSettledUntilDate(v)
	})
}

// UpdateSettledUntilDate sets the "settled_until_date" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertOne) UpdateSettledUntilDate() *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateSettledUntilDate()
	})
}

// ClearSettledUntilDate clears the value of the "settled_until_date" field.
func (u *UserBalanceCreditUpsertOne) ClearSettledUntilDate() *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.ClearSettledUntilDate()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserBalanceCreditUpsertOne) SetExpiresAt(v time.Time) *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertOne) UpdateExpiresAt() *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UserBalanceCreditUpsertOne) ClearExpiresAt() *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.ClearExpiresAt()
	})
}

// SetExpiredAt sets the "expired_at" field.
func (u *UserBalanceCreditUpsertOne) SetExpiredAt(v time.Time) *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetExpiredAt(v)
	})
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertOne) UpdateExpiredAt() *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateExpiredAt()
	})
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (u *UserBalanceCreditUpsertOne) ClearExpiredAt() *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.ClearExpiredAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserBalanceCreditUpsertOne) SetStatus(v string) *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertOne) UpdateStatus() *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserBalanceCreditUpsertOne) SetUpdatedAt(v time.Time) *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertOne) UpdateUpdatedAt() *UserBalanceCreditUpsertOne {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserBalanceCreditUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserBalanceCreditCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserBalanceCreditUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserBalanceCreditUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserBalanceCreditUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserBalanceCreditCreateBulk is the builder for creating many UserBalanceCredit entities in bulk.
type UserBalanceCreditCreateBulk struct {
	config
	err      error
	builders []*UserBalanceCreditCreate
	conflict []sql.ConflictOption
}

// Save creates the UserBalanceCredit entities in the database.
func (_c *UserBalanceCreditCreateBulk) Save(ctx context.Context) ([]*UserBalanceCredit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserBalanceCredit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserBalanceCreditMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserBalanceCreditCreateBulk) SaveX(ctx context.Context) []*UserBalanceCredit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserBalanceCreditCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserBalanceCreditCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserBalanceCredit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserBalanceCreditUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserBalanceCreditCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserBalanceCreditUpsertBulk {
	_c.conflict = opts
	return &UserBalanceCreditUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserBalanceCredit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserBalanceCreditCreateBulk) OnConflictColumns(columns ...string) *UserBalanceCreditUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserBalanceCreditUpsertBulk{
		create: _c,
	}
}

// UserBalanceCreditUpsertBulk is the builder for "upsert"-ing
// a bulk of UserBalanceCredit nodes.
type UserBalanceCreditUpsertBulk struct {
	create *UserBalanceCreditCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserBalanceCredit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserBalanceCreditUpsertBulk) UpdateNewValues() *UserBalanceCreditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userbalancecredit.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserBalanceCredit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserBalanceCreditUpsertBulk) Ignore() *UserBalanceCreditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserBalanceCreditUpsertBulk) DoNothing() *UserBalanceCreditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserBalanceCreditCreateBulk.OnConflict
// documentation for more info.
func (u *UserBalanceCreditUpsertBulk) Update(set func(*UserBalanceCreditUpsert)) *UserBalanceCreditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserBalanceCreditUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserBalanceCreditUpsertBulk) SetUserID(v int64) *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertBulk) UpdateUserID() *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateUserID()
	})
}

// SetSourceType sets the "source_type" field.
func (u *UserBalanceCreditUpsertBulk) SetSourceType(v string) *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertBulk) UpdateSourceType() *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceID sets the "source_id" field.
func (u *UserBalanceCreditUpsertBulk) SetSourceID(v string) *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertBulk) UpdateSourceID() *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateSourceID()
	})
}

// SetSourceCode sets the "source_code" field.
func (u *UserBalanceCreditUpsertBulk) SetSourceCode(v string) *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetSourceCode(v)
	})
}

// UpdateSourceCode sets the "source_code" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertBulk) UpdateSourceCode() *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateSourceCode()
	})
}

// SetAmount sets the "amount" field.
func (u *UserBalanceCreditUpsertBulk) SetAmount(v float64) *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *UserBalanceCreditUpsertBulk) AddAmount(v float64) *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertBulk) UpdateAmount() *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateAmount()
	})
}

// SetRemainingAmount sets the "remaining_amount" field.
func (u *UserBalanceCreditUpsertBulk) SetRemainingAmount(v float64) *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetRemainingAmount(v)
	})
}

// AddRemainingAmount adds v to the "remaining_amount" field.
func (u *UserBalanceCreditUpsertBulk) AddRemainingAmount(v float64) *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.AddRemainingAmount(v)
	})
}

// UpdateRemainingAmount sets the "remaining_amount" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertBulk) UpdateRemainingAmount() *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateRemainingAmount()
	})
}

// SetSettledUntilDate sets the "settled_until_date" field.
func (u *UserBalanceCreditUpsertBulk) SetSettledUntilDate(v time.Time) *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetSettledUntilDate(v)
	})
}

// UpdateSettledUntilDate sets the "settled_until_date" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertBulk) UpdateSettledUntilDate() *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateSettledUntilDate()
	})
}

// ClearSettledUntilDate clears the value of the "settled_until_date" field.
func (u *UserBalanceCreditUpsertBulk) ClearSettledUntilDate() *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.ClearSettledUntilDate()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserBalanceCreditUpsertBulk) SetExpiresAt(v time.Time) *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertBulk) UpdateExpiresAt() *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UserBalanceCreditUpsertBulk) ClearExpiresAt() *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.ClearExpiresAt()
	})
}

// SetExpiredAt sets the "expired_at" field.
func (u *UserBalanceCreditUpsertBulk) SetExpiredAt(v time.Time) *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetExpiredAt(v)
	})
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertBulk) UpdateExpiredAt() *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateExpiredAt()
	})
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (u *UserBalanceCreditUpsertBulk) ClearExpiredAt() *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.ClearExpiredAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserBalanceCreditUpsertBulk) SetStatus(v string) *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertBulk) UpdateStatus() *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserBalanceCreditUpsertBulk) SetUpdatedAt(v time.Time) *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserBalanceCreditUpsertBulk) UpdateUpdatedAt() *UserBalanceCreditUpsertBulk {
	return u.Update(func(s *UserBalanceCreditUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserBalanceCreditUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserBalanceCreditCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserBalanceCreditCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserBalanceCreditUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
