// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userbalancecredit"
)

// UserBalanceCredit is the model entity for the UserBalanceCredit schema.
type UserBalanceCredit struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType string `json:"source_type,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID string `json:"source_id,omitempty"`
	// SourceCode holds the value of the "source_code" field.
	SourceCode string `json:"source_code,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// RemainingAmount holds the value of the "remaining_amount" field.
	RemainingAmount float64 `json:"remaining_amount,omitempty"`
	// SettledUntilDate holds the value of the "settled_until_date" field.
	SettledUntilDate *time.Time `json:"settled_until_date,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// ExpiredAt holds the value of the "expired_at" field.
	ExpiredAt *time.Time `json:"expired_at,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserBalanceCreditQuery when eager-loading is set.
	Edges        UserBalanceCreditEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserBalanceCreditEdges holds the relations/edges for other nodes in the graph.
type UserBalanceCreditEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserBalanceCreditEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserBalanceCredit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userbalancecredit.FieldAmount, userbalancecredit.FieldRemainingAmount:
			values[i] = new(sql.NullFloat64)
		case userbalancecredit.FieldID, userbalancecredit.FieldUserID:
			values[i] = new(sql.NullInt64)
		case userbalancecredit.FieldSourceType, userbalancecredit.FieldSourceID, userbalancecredit.FieldSourceCode, userbalancecredit.FieldStatus:
			values[i] = new(sql.NullString)
		case userbalancecredit.FieldSettledUntilDate, userbalancecredit.FieldExpiresAt, userbalancecredit.FieldExpiredAt, userbalancecredit.FieldCreatedAt, userbalancecredit.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserBalanceCredit fields.
func (_m *UserBalanceCredit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userbalancecredit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case userbalancecredit.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case userbalancecredit.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = value.String
			}
		case userbalancecredit.FieldSourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = value.String
			}
		case userbalancecredit.FieldSourceCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_code", values[i])
			} else if value.Valid {
				_m.SourceCode = value.String
			}
		case userbalancecredit.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case userbalancecredit.FieldRemainingAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field remaining_amount", values[i])
			} else if value.Valid {
				_m.RemainingAmount = value.Float64
			}
		case userbalancecredit.FieldSettledUntilDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field settled_until_date", values[i])
			} else if value.Valid {
				_m.SettledUntilDate = new(time.Time)
				*_m.SettledUntilDate = value.Time
			}
		case userbalancecredit.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case userbalancecredit.FieldExpiredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expired_at", values[i])
			} else if value.Valid {
				_m.ExpiredAt = new(time.Time)
				*_m.ExpiredAt = value.Time
			}
		case userbalancecredit.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case userbalancecredit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userbalancecredit.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserBalanceCredit.
// This includes values selected through modifiers, order, etc.
func (_m *UserBalanceCredit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserBalanceCredit entity.
func (_m *UserBalanceCredit) QueryUser() *UserQuery {
	return NewUserBalanceCreditClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserBalanceCredit.
// Note that you need to call UserBalanceCredit.Unwrap() before calling this method if this UserBalanceCredit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserBalanceCredit) Update() *UserBalanceCreditUpdateOne {
	return NewUserBalanceCreditClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserBalanceCredit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserBalanceCredit) Unwrap() *UserBalanceCredit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserBalanceCredit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserBalanceCredit) String() string {
	var builder strings.Builder
	builder.WriteString("UserBalanceCredit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(_m.SourceType)
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(_m.SourceID)
	builder.WriteString(", ")
	builder.WriteString("source_code=")
	builder.WriteString(_m.SourceCode)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("remaining_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RemainingAmount))
	builder.WriteString(", ")
	if v := _m.SettledUntilDate; v != nil {
		builder.WriteString("settled_until_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiredAt; v != nil {
		builder.WriteString("expired_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserBalanceCredits is a parsable slice of UserBalanceCredit.
type UserBalanceCredits []*UserBalanceCredit
