// Code generated by ent, DO NOT EDIT.

package userbalancecredit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldUserID, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldEmail, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldSourceType, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldSourceID, v))
}

// SourceCode applies equality check predicate on the "source_code" field. It's identical to SourceCodeEQ.
func SourceCode(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldSourceCode, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldAmount, v))
}

// RemainingAmount applies equality check predicate on the "remaining_amount" field. It's identical to RemainingAmountEQ.
func RemainingAmount(v float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldRemainingAmount, v))
}

// SettledUntilDate applies equality check predicate on the "settled_until_date" field. It's identical to SettledUntilDateEQ.
func SettledUntilDate(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldSettledUntilDate, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiredAt applies equality check predicate on the "expired_at" field. It's identical to ExpiredAtEQ.
func ExpiredAt(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldExpiredAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNotIn(FieldUserID, vs...))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldContainsFold(FieldEmail, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDContains applies the Contains predicate on the "source_id" field.
func SourceIDContains(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldContains(FieldSourceID, v))
}

// SourceIDHasPrefix applies the HasPrefix predicate on the "source_id" field.
func SourceIDHasPrefix(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldHasPrefix(FieldSourceID, v))
}

// SourceIDHasSuffix applies the HasSuffix predicate on the "source_id" field.
func SourceIDHasSuffix(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldHasSuffix(FieldSourceID, v))
}

// SourceIDEqualFold applies the EqualFold predicate on the "source_id" field.
func SourceIDEqualFold(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEqualFold(FieldSourceID, v))
}

// SourceIDContainsFold applies the ContainsFold predicate on the "source_id" field.
func SourceIDContainsFold(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldContainsFold(FieldSourceID, v))
}

// SourceCodeEQ applies the EQ predicate on the "source_code" field.
func SourceCodeEQ(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldSourceCode, v))
}

// SourceCodeNEQ applies the NEQ predicate on the "source_code" field.
func SourceCodeNEQ(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNEQ(FieldSourceCode, v))
}

// SourceCodeIn applies the In predicate on the "source_code" field.
func SourceCodeIn(vs ...string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldIn(FieldSourceCode, vs...))
}

// SourceCodeNotIn applies the NotIn predicate on the "source_code" field.
func SourceCodeNotIn(vs ...string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNotIn(FieldSourceCode, vs...))
}

// SourceCodeGT applies the GT predicate on the "source_code" field.
func SourceCodeGT(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGT(FieldSourceCode, v))
}

// SourceCodeGTE applies the GTE predicate on the "source_code" field.
func SourceCodeGTE(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGTE(FieldSourceCode, v))
}

// SourceCodeLT applies the LT predicate on the "source_code" field.
func SourceCodeLT(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLT(FieldSourceCode, v))
}

// SourceCodeLTE applies the LTE predicate on the "source_code" field.
func SourceCodeLTE(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLTE(FieldSourceCode, v))
}

// SourceCodeContains applies the Contains predicate on the "source_code" field.
func SourceCodeContains(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldContains(FieldSourceCode, v))
}

// SourceCodeHasPrefix applies the HasPrefix predicate on the "source_code" field.
func SourceCodeHasPrefix(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldHasPrefix(FieldSourceCode, v))
}

// SourceCodeHasSuffix applies the HasSuffix predicate on the "source_code" field.
func SourceCodeHasSuffix(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldHasSuffix(FieldSourceCode, v))
}

// SourceCodeEqualFold applies the EqualFold predicate on the "source_code" field.
func SourceCodeEqualFold(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEqualFold(FieldSourceCode, v))
}

// SourceCodeContainsFold applies the ContainsFold predicate on the "source_code" field.
func SourceCodeContainsFold(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldContainsFold(FieldSourceCode, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLTE(FieldAmount, v))
}

// RemainingAmountEQ applies the EQ predicate on the "remaining_amount" field.
func RemainingAmountEQ(v float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldRemainingAmount, v))
}

// RemainingAmountNEQ applies the NEQ predicate on the "remaining_amount" field.
func RemainingAmountNEQ(v float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNEQ(FieldRemainingAmount, v))
}

// RemainingAmountIn applies the In predicate on the "remaining_amount" field.
func RemainingAmountIn(vs ...float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldIn(FieldRemainingAmount, vs...))
}

// RemainingAmountNotIn applies the NotIn predicate on the "remaining_amount" field.
func RemainingAmountNotIn(vs ...float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNotIn(FieldRemainingAmount, vs...))
}

// RemainingAmountGT applies the GT predicate on the "remaining_amount" field.
func RemainingAmountGT(v float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGT(FieldRemainingAmount, v))
}

// RemainingAmountGTE applies the GTE predicate on the "remaining_amount" field.
func RemainingAmountGTE(v float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGTE(FieldRemainingAmount, v))
}

// RemainingAmountLT applies the LT predicate on the "remaining_amount" field.
func RemainingAmountLT(v float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLT(FieldRemainingAmount, v))
}

// RemainingAmountLTE applies the LTE predicate on the "remaining_amount" field.
func RemainingAmountLTE(v float64) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLTE(FieldRemainingAmount, v))
}

// SettledUntilDateEQ applies the EQ predicate on the "settled_until_date" field.
func SettledUntilDateEQ(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldSettledUntilDate, v))
}

// SettledUntilDateNEQ applies the NEQ predicate on the "settled_until_date" field.
func SettledUntilDateNEQ(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNEQ(FieldSettledUntilDate, v))
}

// SettledUntilDateIn applies the In predicate on the "settled_until_date" field.
func SettledUntilDateIn(vs ...time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldIn(FieldSettledUntilDate, vs...))
}

// SettledUntilDateNotIn applies the NotIn predicate on the "settled_until_date" field.
func SettledUntilDateNotIn(vs ...time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNotIn(FieldSettledUntilDate, vs...))
}

// SettledUntilDateGT applies the GT predicate on the "settled_until_date" field.
func SettledUntilDateGT(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGT(FieldSettledUntilDate, v))
}

// SettledUntilDateGTE applies the GTE predicate on the "settled_until_date" field.
func SettledUntilDateGTE(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGTE(FieldSettledUntilDate, v))
}

// SettledUntilDateLT applies the LT predicate on the "settled_until_date" field.
func SettledUntilDateLT(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLT(FieldSettledUntilDate, v))
}

// SettledUntilDateLTE applies the LTE predicate on the "settled_until_date" field.
func SettledUntilDateLTE(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLTE(FieldSettledUntilDate, v))
}

// SettledUntilDateIsNil applies the IsNil predicate on the "settled_until_date" field.
func SettledUntilDateIsNil() predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldIsNull(FieldSettledUntilDate))
}

// SettledUntilDateNotNil applies the NotNil predicate on the "settled_until_date" field.
func SettledUntilDateNotNil() predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNotNull(FieldSettledUntilDate))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNotNull(FieldExpiresAt))
}

// ExpiredAtEQ applies the EQ predicate on the "expired_at" field.
func ExpiredAtEQ(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldExpiredAt, v))
}

// ExpiredAtNEQ applies the NEQ predicate on the "expired_at" field.
func ExpiredAtNEQ(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNEQ(FieldExpiredAt, v))
}

// ExpiredAtIn applies the In predicate on the "expired_at" field.
func ExpiredAtIn(vs ...time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldIn(FieldExpiredAt, vs...))
}

// ExpiredAtNotIn applies the NotIn predicate on the "expired_at" field.
func ExpiredAtNotIn(vs ...time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNotIn(FieldExpiredAt, vs...))
}

// ExpiredAtGT applies the GT predicate on the "expired_at" field.
func ExpiredAtGT(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGT(FieldExpiredAt, v))
}

// ExpiredAtGTE applies the GTE predicate on the "expired_at" field.
func ExpiredAtGTE(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGTE(FieldExpiredAt, v))
}

// ExpiredAtLT applies the LT predicate on the "expired_at" field.
func ExpiredAtLT(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLT(FieldExpiredAt, v))
}

// ExpiredAtLTE applies the LTE predicate on the "expired_at" field.
func ExpiredAtLTE(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLTE(FieldExpiredAt, v))
}

// ExpiredAtIsNil applies the IsNil predicate on the "expired_at" field.
func ExpiredAtIsNil() predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldIsNull(FieldExpiredAt))
}

// ExpiredAtNotNil applies the NotNil predicate on the "expired_at" field.
func ExpiredAtNotNil() predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNotNull(FieldExpiredAt))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserBalanceCredit) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserBalanceCredit) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserBalanceCredit) predicate.UserBalanceCredit {
	return predicate.UserBalanceCredit(sql.NotPredicates(p))
}
